### AspectJ缺陷 ###

### 无限循环 ###


这是一个具有特殊行为的Java程序

	public class Main {
	    public static void main(String[] args) {
	        foo();
	        System.out.println("done with call to foo");
	    }
	
	    static void foo() {
	        try {
	            foo();
	        } finally {
	            foo();
	        }
	    }

这个程序永远不会到达println调用，但是当它中止时可能没有堆栈跟踪。

这种沉默是由多个StackOverflowExceptions引起的。 首先，方法体内的无限循环生成一个，finally子句试图处理该循环。 但是这个finally子句也会产生一个无限循环，目前的JVM无法正常处理，从而导致完全无声的中止。

以下简短的方面也会产生这种行为：

	aspect A {
	    before(): call(* *(..)) { System.out.println("before"); }
	    after():  call(* *(..)) { System.out.println("after"); }
	}

为什么？ 因为对println的调用也是由切入点调用**call (* *(..))**匹配的调用。 由于我们使用了简化的**after（）**建议，所以我们没有输出。 如果切面改变为

	aspect A {
	    before(): call(* *(..)) { System.out.println("before"); }
	    after() returning:  call(* *(..)) { System.out.println("after"); }
	}

然后至少会看到一个带有堆栈跟踪的StackOverflowException。 但是，在这两种情况下，总体问题都是在自己的身体内应用的通知。

如果您担心您的建议可能会以这种方式应用，那么有一个简单的习惯用法。 只要限制在该方面引起的连接点发生的建议。 所以：

	aspect A {
	    before(): call(* *(..)) && !within(A) { System.out.println("before"); }
	    after() returning:  call(* *(..)) && !within(A) { System.out.println("after"); }
	}

其他解决方案可能会以其他方式更紧密地限制切入点，例如：

	aspect A {
	    before(): call(* MyObject.*(..))  { System.out.println("before"); }
	    after() returning:  call(* MyObject.*(..))  { System.out.println("after"); }
	}

故事的寓意是，不受限制的通用切入点可以挑选出比预期更多的连接点。
